
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jun 27 18:28:49 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 8;
  public static final int CONST = 6;
  public static final int GE = 33;
  public static final int YIELD = 22;
  public static final int NUMCONST = 48;
  public static final int CASE = 38;
  public static final int CONTINUE = 47;
  public static final int LPAREN = 9;
  public static final int SEMI = 18;
  public static final int MINUS = 24;
  public static final int RPAREN = 10;
  public static final int AND = 41;
  public static final int LT = 30;
  public static final int OR = 40;
  public static final int COMMA = 13;
  public static final int CLASS = 42;
  public static final int INC = 25;
  public static final int DIV = 28;
  public static final int PLUS = 23;
  public static final int ASSIGN = 11;
  public static final int IF = 16;
  public static final int LE = 32;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 35;
  public static final int RBRACKET = 7;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int DIF = 34;
  public static final int MOD = 29;
  public static final int IDENT = 51;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int SWITCH = 37;
  public static final int COLON = 20;
  public static final int LBRACE = 4;
  public static final int ELSE = 17;
  public static final int ENUM = 43;
  public static final int READ = 19;
  public static final int CHARCONST = 49;
  public static final int WHILE = 45;
  public static final int DEFAULT = 21;
  public static final int RBRACE = 5;
  public static final int BOOLCONST = 50;
  public static final int EXTENDS = 46;
  public static final int PROG = 2;
  public static final int QUESTION = 39;
  public static final int DEC = 26;
  public static final int GT = 31;
  public static final int DO = 44;
  public static final int PRINT = 14;
}

